apiVersion: apps/v1
kind: Deployment
metadata:
 name: LAB-IBM
spec:
 replicas: 2
 selector:
     matchLabels:
       app: LAB-IBM
 template:
   metadata:
     labels:
       app: LAB-IBM
   spec:     # pod spec                  
     containers:
     - name: hello-containers
       image: us.icr.io/cldstd37-ns/hello-containers-20200623155903894:latest
       ports:
         - containerPort: 8080
       env:
         - name: APIKEY
           value: bj15rcA-dr7EY3nCWZBTGlGUo1lz08ddU7fxHepL9JrW
         - name: URL
           value: https://api.us-south.assistant.watson.cloud.ibm.com/instances/73d81d29-458c-451d-8bb2-e079ab2f762e
         - name: ASSISTANT_ID
           value: 25f1e69d-8ec3-4181-8b1a-9c548ac3baef
       imagePullPolicy: Always
